Update scientific literacy chapter with revisions and extensions
PathOS-project/indicator_handbook pull request #78
Opened 2024-12-16 12:48 UTC by ekormann

Integrate major revisions and extensions into section on scientific literacy together with extended literature
#33

2024-12-16 13:57 UTC, tklebel requested changes
Thanks Eva! There are a small minor changes to finish this up.

2024-12-16 13:57 UTC, tklebel commented on sections/3_societal_impact/scientific_literacy.qmd
> +First, in a view proposed by @laugksch2000 and supported by @roberts2007, there are at least three stakeholder groups engaged with scientific literacy: (1) sociologists, (2) public opinion researcher
You lost the trailing dot in the last sentence.

2024-12-16 13:57 UTC, tklebel commented on sections/3_societal_impact/scientific_literacy.qmd
> +Third, @roberts2007 provides a useful distinction between two “Visions” of scientific literacy. Here the term “Vision” is broader than a mere definition and represents an ideal type in the Weberian s
The italics for "thoroguh knowledgability" where lost. Please check the original version.

2024-12-16 13:57 UTC, tklebel commented on sections/3_societal_impact/scientific_literacy.qmd
> +Third, @roberts2007 provides a useful distinction between two “Visions” of scientific literacy. Here the term “Vision” is broader than a mere definition and represents an ideal type in the Weberian s
This is the original: 

```
read *thorough knowledgeability*) *about science-related situations*
```

2024-12-16 14:34 UTC, tklebel commented
Hi @vtraag this should be good to merge now. Maybe have another look - I just looked at the text, not sure whether there is anything else you usually check.

2024-12-17 09:37 UTC, vtraag approved these changes
Looks good to me as well, thanks @ekormann ! I've made some minor changes (replacing quotes essentially) and cleaning up the bibtex. Assuming you have no problems with those changes, we can get this merged. I'll merge it later today, unless I hear from you.

2024-12-18 09:01 UTC, merged